
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "SWSIFACE"
  end
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
  config.vm.box_check_update = false
  config.vm.synced_folder "./data", "/vagrant_data"
  config.vm.hostname = "vagrant-docker"
  config.vm.provider "docker" do |d|
    d.has_ssh = true
    d.build_dir = "."
    d.remains_running = false
    d.cmd = ["tail", "-f", "/dev/null"]
  end
  config.vm.network "forwarded_port", guest: 80, host: 8585
  config.ssh.insert_key = false
  config.ssh.private_key_path = [
    '~/.ssh/id_rsa',
    '~/.vagrant.d/insecure_private_key'
  ]
  config.vm.provision 'file', 
    source: '~/.ssh/id_rsa.pub', 
    destination: '~/.ssh/authorized_keys'
end


